[tasks.test]
command = "wasm-pack"
args = ["test", "--chrome", "--headless"]

[tasks.build]
command = "wasm-pack"
args = ["build", "--dev", "--target", "web", "--out-name", "app"]

[tasks.bundle]
command = "npm"
args = ["run", "build"]

[tasks.serve]
command = "npm"
args = ["run", "start"]

[tasks.cargo-clean]
command = "cargo"
args = ["clean"]

[tasks.node-clean]
command = "rm"
args = ["-rf", "node_modules"]

[tasks.dist-clean]
command = "rm"
args = ["-rf", "dist"]

[tasks.clean]
dependencies = ["cargo-clean", "node-clean", "dist-clean"]
command = "rm"
args = ["-rf", "pkg"]
